-- Bootstrap script for apps/tma Supabase demo data.
-- Run in Supabase SQL Editor for the target project.

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

drop policy if exists "anon can read todos" on public.todos;
create policy "anon can read todos"
on public.todos
for select
to anon
using (true);

insert into public.todos (name)
values
  ('Complete onboarding'),
  ('Run first diagnosis'),
  ('Start mobility routine')
on conflict do nothing;
